### ISSUE TITLE
variant restriction boolean bug

### ISSUE THREAD

**Issue by alisonjoseph** [figma/code-connect#45]
I'm getting the following error when trying to create a variant restriction with a boolean property
`The Figma Variant "Actionable" does not have an option for true`

When creating my code connect file the property comes through: `figma.boolean('Actionable')`, and I can see it in Figma also. Is this a bug, or is my implementation incorrect?

```js
figma.connect(
  ActionableNotification,
  'https://www.figma.com...',
  {
    variant: { Actionable: true },
    props: sharedNotificationProps,
    example: ({ title, kind, subtitle, hideCloseButton }) => (
      <ActionableNotification
        kind={kind}
        title={title}
        subtitle={subtitle}
        hideCloseButton={hideCloseButton}
      />
    ),
  }
);
```

**Comment by tomduncalf-figma** [comment]
Hey @alisonjoseph, I think what could be going on here is that your property in Figma is actually a variant with "boolean-like string values" rather than a true boolean. It might be the string `"True"` or `"Yes"` or something like that.

We automatically translate these "boolean-like" strings to boolean values when using `figma.boolean`, but I don't think we do the same for variant restrictions, so you'd need to specify the literal value from Figma e.g. `variant: { Actionable: "True" }`.

I think this is something we should fix, so that the API is consistent across props and variant restrictions.

Feel free to share a screenshot of your component's properties in Figma if you're not sure, and if this isn't the case we'd be happy to investigate further.

**Comment by alisonjoseph** [comment]
This appears to be working / fixed. thanks!
